export type CurriculumCategory = "core" | "future" | "creative" | "life"
export type CurriculumFilter = "all" | CurriculumCategory

export interface CurriculumSubject {
  name: string
  cat: CurriculumCategory
  color: string
  content: Record<number, string[]>
}

export type CurriculumData = Record<string, CurriculumSubject>

export const bands: Record<number, string> = {
  4: "Little Explorers",
  5: "Little Explorers",
  6: "Young Discoverers",
  7: "Young Discoverers",
  8: "Curious Minds",
  9: "Curious Minds",
  10: "Junior Scholars",
  11: "Junior Scholars",
  12: "Future Leaders",
  13: "Future Leaders",
}

export const catColors: Record<CurriculumCategory, string> = {
  core: "#1D9E75",
  future: "#378ADD",
  creative: "#BA7517",
  life: "#E24B4A",
}

export const catLabels: Record<CurriculumCategory, string> = {
  core: "Core",
  future: "Future Skills",
  creative: "Creative",
  life: "Life & Growth",
}

export const curriculumData: CurriculumData = {
  english: {
    name: "English",
    cat: "core",
    color: "#1D9E75",
    content: {
      4: ["Letter recognition A-Z", "Phonics: short vowel sounds", "Simple sight words (the, is, a)", "Picture book reading", "Oral storytelling with prompts"],
      5: ["Blending CVC words", "Sight word sentences", "Read-aloud comprehension", "Name writing & simple words", "Rhyming and word families"],
      6: ["Short story reading", "Basic punctuation (. ! ?)", "Simple sentence writing", "Consonant blends (bl, cr, st)", "Creative drawing + caption"],
      7: ["Paragraph reading", "Nouns, verbs, adjectives", "Journal writing (3-5 sentences)", "Main idea & details", "Spelling patterns"],
      8: ["Chapter book reading", "Subject & predicate", "Personal narrative writing", "Synonyms and antonyms", "Introduction to dialogue"],
      9: ["Fiction vs non-fiction", "Parts of speech review", "5-sentence paragraph", "Context clues for vocabulary", "Summarising stories"],
      10: ["Novel reading & analysis", "Compound & complex sentences", "Opinion / persuasive writing", "Prefixes & suffixes", "Literary devices: simile, metaphor"],
      11: ["Literary genres", "Thesis statements", "Research writing basics", "Vocabulary in context", "Point of view & perspective"],
      12: ["Analysing arguments", "Essay structure (intro/body/conclusion)", "Figurative language in depth", "Active vs passive voice", "Poetry analysis"],
      13: ["Critical reading & evaluation", "Persuasive & expository essays", "Advanced grammar", "Citation & bibliography basics", "Debate writing"],
    },
  },
  math: {
    name: "Math",
    cat: "core",
    color: "#1D9E75",
    content: {
      4: ["Counting 1-20", "Shapes: circle, square, triangle", "Comparing more/less", "Simple addition to 5", "Patterns (AB, ABC)"],
      5: ["Counting to 100", "Addition & subtraction to 10", "2D vs 3D shapes", "Measurement: long/short", "Introduction to time (o'clock)"],
      6: ["Place value: tens & ones", "Addition to 100", "Skip counting (2s, 5s, 10s)", "Telling time to half hour", "Simple graphs & charts"],
      7: ["3-digit numbers", "Multiplication concept (groups of)", "Fractions: half, quarter", "Measurement: cm & m", "Word problems (1-step)"],
      8: ["Multiplication tables 1-10", "Long division intro", "Fractions: compare & order", "Perimeter & area basics", "Word problems (2-step)"],
      9: ["Multiplication tables mastery", "Fractions: add & subtract", "Decimals: tenths, hundredths", "Basic geometry (angles)", "Data: mean, median, mode"],
      10: ["Long division", "Fractions x decimals", "Ratio & proportion", "Introduction to percentages", "Area of complex shapes"],
      11: ["Negative numbers", "Algebra: solving for x", "Percentage applications", "Probability basics", "Coordinate graphing"],
      12: ["Linear equations", "Geometry: angles & triangles", "Statistics: charts & analysis", "Ratio & rate problems", "Introduction to functions"],
      13: ["Quadratic expressions", "Systems of equations", "Surface area & volume", "Probability & data analysis", "Financial math basics"],
    },
  },
  science: {
    name: "Science",
    cat: "core",
    color: "#1D9E75",
    content: {
      4: ["Living vs non-living things", "My five senses", "Weather: sunny, rainy, cloudy", "Plants need water & sun", "Animals and their homes"],
      5: ["Plant parts & growth", "Animal groups (mammals, birds)", "Seasons and weather", "Day & night cycle", "Simple experiments: sink/float"],
      6: ["Life cycles (butterfly, frog)", "Food chains basics", "Matter: solid, liquid, gas", "Sun, moon & stars intro", "Habitats & ecosystems"],
      7: ["Human body systems overview", "Photosynthesis basics", "States of matter & changes", "Solar system & planets", "Simple machines"],
      8: ["Cell basics (animal/plant)", "Food webs & ecosystems", "Energy: light, heat, sound", "Earth's layers", "Forces: push & pull"],
      9: ["Genetics intro (traits)", "Ecosystems & biomes", "Chemical reactions basics", "Water cycle in depth", "Motion & gravity"],
      10: ["Cell division basics", "Adaptation & evolution", "Periodic table intro", "Weather & climate systems", "Electricity & circuits"],
      11: ["Body systems in depth", "Ecology & environment", "Atoms & molecules", "Earth science: rocks & fossils", "Physics: speed & acceleration"],
      12: ["DNA & heredity", "Natural selection", "Chemical bonds & reactions", "Climate change & solutions", "Waves: light & sound"],
      13: ["Biotechnology & ethics", "Environmental science", "Organic chemistry intro", "Physics: energy & thermodynamics", "Scientific inquiry & research"],
    },
  },
  social: {
    name: "Social Studies",
    cat: "core",
    color: "#1D9E75",
    content: {
      4: ["My family & community", "School & neighbourhood rules", "Basic map: home & school", "Community helpers", "Holidays & traditions"],
      5: ["My city & country", "Maps: continents & oceans", "Needs vs wants", "Cultural celebrations", "Symbols of our nation"],
      6: ["World continents overview", "Ancient civilisations intro", "Government roles (leader, rules)", "World cultures & customs", "Natural resources"],
      7: ["World history: early humans", "Introduction to geography", "Communities around the world", "Economics: trade basics", "Rules & laws"],
      8: ["Ancient civilisations (Egypt, Greece)", "Map skills: latitude & longitude", "Economies & resources", "Democracy basics", "Cause & effect in history"],
      9: ["Medieval history", "World religions overview", "Supply & demand", "Government systems", "Geography: climate & culture"],
      10: ["Renaissance & Exploration", "Human rights basics", "Global economics intro", "Civics: rights & responsibilities", "Comparing world cultures"],
      11: ["Industrial Revolution", "World War I & II overview", "International organisations (UN)", "Economics: markets & trade", "Migration & identity"],
      12: ["Cold War & modern history", "Political systems compared", "Globalisation", "Media literacy & bias", "Social issues & advocacy"],
      13: ["Contemporary world history", "Geopolitics basics", "Economic systems", "Civic engagement", "Research & debate on current events"],
    },
  },
  coding: {
    name: "Coding",
    cat: "future",
    color: "#378ADD",
    content: {
      4: ["What is a computer?", "Unplugged: sequencing activities", "Simple patterns & algorithms", "Introduction to a mouse/tablet", "Drawing with basic tools"],
      5: ["Block coding (Scratch Jr)", "Sequences: step-by-step instructions", "Loops: repeat actions", "Simple animations", "Debugging: spot the mistake"],
      6: ["Scratch: events & sprites", "Conditionals: if/then", "Creating a simple game", "Loops in action", "Sharing & presenting projects"],
      7: ["Scratch projects with variables", "Introduction to HTML basics", "What is a website?", "Nested loops", "Mini project: interactive story"],
      8: ["HTML: tags, headings, paragraphs", "CSS: color & font basics", "Scratch: score-keeping game", "Algorithms & flowcharts", "Introduction to Python (turtle)"],
      9: ["Python: variables & data types", "HTML + CSS mini website", "Loops in Python", "Functions basics", "Debugging strategies"],
      10: ["Python: lists & conditionals", "Building a text-based game", "Introduction to APIs (concept)", "Functions & reusability", "Version control basics (Git intro)"],
      11: ["Python: file handling", "Web development: HTML/CSS/JS", "Object-oriented concepts", "Intro to databases (SQL basics)", "Project: simple app"],
      12: ["Python projects (data/automation)", "JavaScript basics", "APIs: fetch & display data", "Problem-solving with algorithms", "Agile project basics"],
      13: ["Full project: web or Python app", "Data structures & algorithms", "Introduction to machine learning concepts", "App deployment basics", "Tech ethics & responsible coding"],
    },
  },
  ai: {
    name: "AI",
    cat: "future",
    color: "#378ADD",
    content: {
      4: ["What is a robot?", "Machines that help us", "Computers that listen (Siri/Alexa)", "Smart vs not-smart devices", "Fun with AI art tools"],
      5: ["How computers learn from examples", "AI in everyday life", "Voice assistants: how do they work?", "Recommendation: why does YouTube suggest videos?", "AI as a helper"],
      6: ["What is data? Why do computers need it?", "How AI recognises pictures", "AI in games", "AI helpers vs human helpers", "Creating with AI tools"],
      7: ["Introduction to machine learning concept", "Training data basics", "AI in medicine & science", "Bias in AI (simple intro)", "Build a simple classifier (Teachable Machine)"],
      8: ["Supervised vs unsupervised learning (concept)", "AI in self-driving cars", "How chatbots work", "Data privacy basics", "Hands-on: train an image model"],
      9: ["Neural networks: how the brain inspires AI", "Natural language processing basics", "AI in art, music & writing", "Ethical AI: fairness & bias", "Hands-on: text classification"],
      10: ["Algorithms & decision trees", "AI in climate & environment", "Generative AI explained", "How search engines rank results", "Mini-project: AI solution design"],
      11: ["AI lifecycle: data -> model -> deployment", "Deepfakes & misinformation", "AI policy & regulation basics", "Hands-on: simple ML model (Python)", "AI in careers"],
      12: ["Deep learning overview", "Large language models explained", "Responsible AI design", "AI business applications", "Project: AI-powered tool prototype"],
      13: ["AI ethics: advanced debates", "Future of work & automation", "AI in global challenges", "Capstone: propose an AI solution", "Critical evaluation of AI systems"],
    },
  },
  digital: {
    name: "Digital Skills",
    cat: "future",
    color: "#378ADD",
    content: {
      4: ["Using a keyboard & mouse", "Opening & closing apps", "Digital safety: strangers online", "Screen time basics", "Saving & finding files"],
      5: ["Typing practice (home row)", "Taking screenshots", "Safe browsing intro", "Creating a folder", "Introduction to email (concept)"],
      6: ["Internet searches: keywords", "Evaluating websites: is it real?", "Creating a simple document", "Digital citizenship basics", "Introduction to presentations"],
      7: ["Advanced search techniques", "Spreadsheet basics (rows & columns)", "Email etiquette", "Password safety & privacy", "Creating a slideshow"],
      8: ["Research skills: multiple sources", "Spreadsheet: basic formulas", "Online collaboration tools", "Cyber safety: phishing & scams", "Photo editing basics"],
      9: ["Fact-checking & source evaluation", "Spreadsheet: charts & graphs", "Video creation basics", "Digital footprint awareness", "Intro to cloud storage"],
      10: ["Curating credible information", "Data visualisation basics", "Podcast or video project", "Copyright & fair use", "Productivity tools (calendar, notes)"],
      11: ["Media literacy & bias analysis", "Database basics", "Digital project management", "Online privacy tools", "Building a personal learning portfolio"],
      12: ["Advanced media literacy", "Spreadsheet: advanced analysis", "Collaboration on shared projects", "Personal branding online", "Data analysis with real datasets"],
      13: ["Digital research capstone", "Cyber security basics", "Creating a professional digital profile", "Open-source tools & communities", "Evaluating AI-generated content"],
    },
  },
  art: {
    name: "Art",
    cat: "creative",
    color: "#BA7517",
    content: {
      4: ["Finger painting & colour mixing", "Drawing shapes & faces", "Collage with cut paper", "Playdough sculpting", "Favourite things: free draw"],
      5: ["Primary & secondary colours", "Drawing animals from shapes", "Texture rubbings", "Simple printmaking (sponge/stamp)", "Self-portrait"],
      6: ["Colour wheel", "Line types: thick, thin, wavy", "Drawing landscapes", "Basic symmetry", "Art appreciation: famous paintings"],
      7: ["Warm vs cool colours", "Still life drawing", "Introduction to watercolour", "Pattern design", "Art from different cultures"],
      8: ["Perspective: foreground/background", "Shading & shadow basics", "Watercolour & ink mixed media", "Aboriginal & indigenous art forms", "Design a poster"],
      9: ["One-point perspective", "Portrait drawing (proportions)", "Acrylic painting basics", "Graphic design elements (balance, contrast)", "Art movement: Impressionism"],
      10: ["Two-point perspective", "Figure drawing basics", "Digital art tools intro", "Photography composition", "Art movement: Surrealism & Cubism"],
      11: ["Art portfolio development", "Mixed media project", "Photography: lighting & framing", "Design thinking: visual problem solving", "Art history: 20th century movements"],
      12: ["Artist statement writing", "Advanced digital illustration", "Animation basics (flipbook/digital)", "Architecture & spatial design", "Art for social change"],
      13: ["Capstone art project", "Style development & personal voice", "Critique & peer feedback", "Professional portfolio", "Art in the modern world"],
    },
  },
  music: {
    name: "Music",
    cat: "creative",
    color: "#BA7517",
    content: {
      4: ["Clapping rhythms", "High vs low sounds", "Fast vs slow (tempo)", "Songs from around the world", "Body percussion"],
      5: ["Beat vs rhythm", "Instruments: strings, wind, percussion", "Simple melodies (voice/xylophone)", "Music & emotions", "Musical storytelling"],
      6: ["Reading basic notation (ta/ti-ti)", "Singing in groups", "Recorder or keyboard intro", "Dynamics: loud & soft", "Folk music from different countries"],
      7: ["Musical alphabet (A-G)", "Quarter, half & whole notes", "Composing a 4-beat pattern", "Introduction to genres (jazz, classical)", "Listening & responding to music"],
      8: ["Treble clef basics", "Major scale on keyboard", "Simple chord concept", "Music from different eras (Baroque, Classical)", "Create a short melody"],
      9: ["Reading simple sheet music", "Major vs minor (mood)", "Rhythm & metre", "African & world music traditions", "Songwriting: lyrics + melody"],
      10: ["Chord progressions (I-IV-V)", "Music theory: intervals", "Digital music tools (GarageBand/Chrome Music Lab)", "20th century genres (jazz, rock, pop)", "Compose a 16-bar piece"],
      11: ["Harmony & counterpoint intro", "Music production basics", "Analysing song structure (verse/chorus)", "Music in media & film", "Arrange a known piece"],
      12: ["Advanced music theory", "Recording & mixing basics", "Music & identity (cultural expression)", "Improvisation techniques", "Solo or ensemble performance"],
      13: ["Music composition capstone", "Music industry overview", "Critical listening & analysis", "Music technology project", "Personal performance & reflection"],
    },
  },
  life: {
    name: "Life Skills",
    cat: "life",
    color: "#E24B4A",
    content: {
      4: ["Dressing independently", "Brushing teeth & hygiene routine", "Cleaning up after play", "Asking for help politely", "Morning & bedtime routines"],
      5: ["Making a simple snack", "Organising school bag", "Expressing feelings with words", "Following 2-step instructions", "Helping with chores"],
      6: ["Basic cooking safety", "Making my bed", "Time awareness: clocks & schedules", "Showing kindness to others", "Problem-solving: what do I do if..."],
      7: ["Planning a simple meal", "Doing laundry basics", "Managing pocket money", "Responsibility & accountability", "Conflict resolution basics"],
      8: ["Cooking a full simple meal", "Home safety (fire, electrical)", "Setting goals short-term", "Teamwork & cooperation", "Planning & prioritising tasks"],
      9: ["Reading recipes & measuring", "Grocery list & budgeting basics", "Organising study schedule", "Empathy & perspective-taking", "Decision-making framework"],
      10: ["Meal planning for the week", "Emergency contacts & first aid basics", "Stress management techniques", "Leadership in groups", "Long-term goal setting"],
      11: ["Cooking nutritional meals", "Home maintenance basics", "Building positive habits", "Navigating peer pressure", "Self-advocacy skills"],
      12: ["Budgeting a weekly plan", "Volunteering & community contribution", "Time management for projects", "Emotional intelligence", "Career exploration & interests"],
      13: ["Independent living basics", "Environmental responsibility", "Networking & relationships", "Resilience & growth mindset", "Preparing for adulthood"],
    },
  },
  health: {
    name: "Health",
    cat: "life",
    color: "#E24B4A",
    content: {
      4: ["Washing hands & germ basics", "Healthy foods vs treats", "Exercise every day", "Rest & sleep importance", "Safety: road, strangers, home"],
      5: ["Food groups & balanced plate", "Types of exercise (run, swim, play)", "Feelings & emotions", "Sun safety & hygiene", "Visiting the doctor/dentist"],
      6: ["Nutrition: what food does for us", "Bones & muscles", "Mental wellbeing: calm-down strategies", "Substance safety: medicines vs drugs", "Personal space & body safety"],
      7: ["Digestive & respiratory systems", "Fitness: strength & flexibility", "Stress & emotions management", "Internet safety & screen health", "Introduction to puberty (age-appropriate)"],
      8: ["Body systems: heart & lungs", "Nutrition labels & healthy choices", "Mental health: anxiety awareness", "Substance awareness (no to drugs/alcohol)", "First aid: cuts & burns"],
      9: ["Puberty & physical changes", "Nutrient groups & deficiencies", "Exercise science: aerobic vs anaerobic", "Emotional regulation techniques", "Body image & media influence"],
      10: ["Reproductive health basics", "Sports nutrition", "Mental health: depression awareness", "CPR concept & emergency response", "Sleep science & hygiene"],
      11: ["Hormones & health", "Eating disorders awareness", "Mindfulness & meditation", "Substance abuse: effects & risks", "Healthcare navigation"],
      12: ["Chronic disease prevention", "Fitness planning", "Mental health: seeking help", "Relationships & healthy boundaries", "Community health & advocacy"],
      13: ["Personal health responsibility", "Advanced nutrition & fitness", "Mental health in adolescence", "Sexual health & consent", "Global health issues"],
    },
  },
  finance: {
    name: "Finance",
    cat: "life",
    color: "#E24B4A",
    content: {
      4: ["Coins & notes: names & values", "Counting money basics", "Buying things costs money", "Needs vs wants", "Saving in a piggy bank"],
      5: ["Making change (basic)", "Spending vs saving", "Where does money come from?", "Comparing prices", "Simple budgeting: my pocket money"],
      6: ["Earning money (chores, jobs)", "Saving for a goal", "Smart spending choices", "Introduction to banks", "Giving: sharing & charity"],
      7: ["Income & expenses concept", "Creating a simple budget", "Wants vs needs (deeper)", "Sales & discounts", "Introduction to investing (grow money)"],
      8: ["Budgeting: plan the week", "Interest: how savings grow", "Advertising & being a smart shopper", "Bank account basics", "Goal-based saving"],
      9: ["Monthly budget simulation", "Simple interest calculation", "Supply & demand basics", "Tax concept (what it funds)", "Entrepreneurship: business idea"],
      10: ["Compound interest", "Debit vs credit", "Stock market intro", "Business plan basics", "Consumer rights"],
      11: ["Personal finance planning", "Debt & responsible borrowing", "Investing: stocks, bonds, funds", "Budgeting for a trip or project", "Entrepreneurship project"],
      12: ["Income tax basics", "Credit score concept", "Investing for the future", "Insurance: why it matters", "Financial goals: short & long term"],
      13: ["Financial literacy capstone", "Budgeting for independence", "Investment strategies", "Starting a micro-business", "Ethical finance & social responsibility"],
    },
  },
  communication: {
    name: "Communication",
    cat: "life",
    color: "#E24B4A",
    content: {
      4: ["Speaking clearly & taking turns", "Listening when others talk", "Using please & thank you", "Show & tell presentations", "Understanding facial expressions"],
      5: ["Sharing ideas in a group", "Asking good questions", "Non-verbal cues: body language", "Storytelling out loud", "Giving simple feedback"],
      6: ["Introduction to public speaking", "Active listening skills", "Expressing opinions politely", "Writing a friendly letter", "Understanding tone of voice"],
      7: ["Structured speaking (intro/middle/end)", "Group discussion roles", "Constructive feedback", "Formal vs informal language", "Introduction to debate"],
      8: ["2-minute speeches", "Empathetic listening", "Email writing basics", "Persuasive language", "Peer feedback & self-reflection"],
      9: ["Presentations with slides", "Negotiation & compromise", "Written arguments", "Understanding audience", "Interview skills basics"],
      10: ["Research-based presentations", "Cross-cultural communication", "Persuasive speeches", "Conflict resolution through words", "Social media communication"],
      11: ["Formal debates", "Business writing intro", "Storytelling for impact", "Listening in difficult conversations", "Digital communication etiquette"],
      12: ["Leadership communication", "Professional email & letter writing", "TED-style talk preparation", "Media & press literacy", "Networking conversations"],
      13: ["Communication in the workplace", "Advanced writing for different audiences", "Interviewing & being interviewed", "Personal communication brand", "Capstone: public speech or debate"],
    },
  },
}
